In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
from PIL import Image  

In [2]:
caffe_root = '/home/lqp/caffe/'  
import sys  
sys.path.insert(0, caffe_root + 'python')  
import caffe  

In [3]:
caffe.set_mode_cpu()

In [5]:
net = caffe.Net('/home/lqp/caffe/examples/lqp/conv.prototxt', caffe.TEST)  

In [6]:
print type(net) 

<class 'caffe._caffe.Net'>


In [7]:
print dir(net) 

['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_backward', '_batch', '_blob_loss_weights', '_blob_names', '_blobs', '_bottom_ids', '_forward', '_inputs', '_layer_names', '_outputs', '_set_input_arrays', '_top_ids', 'after_backward', 'after_forward', 'backward', 'before_backward', 'before_forward', 'blob_loss_weights', 'blobs', 'bottom_names', 'clear_param_diffs', 'copy_from', 'forward', 'forward_all', 'forward_backward_all', 'inputs', 'layer_dict', 'layers', 'load_hdf5', 'outputs', 'params', 'reshape', 'save', 'save_hdf5', 'set_input_arrays', 'share_with', 'top_names']


In [8]:
print help(net) 

Help on Net in module caffe._caffe object:

class Net(Boost.Python.instance)
 |  Method resolution order:
 |      Net
 |      Boost.Python.instance
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__( (object)arg1, (str)network_file, (int)phase [, (int)level=0 [, (object)stages=None [, (object)weights=None]]]) -> object :
 |      
 |          C++ signature :
 |              void* __init__(boost::python::api::object,std::string,int [,int=0 [,boost::python::api::object=None [,boost::python::api::object=None]]])
 |      
 |      __init__( (object)arg1, (str)arg2, (str)arg3, (int)arg4) -> object :
 |      
 |          C++ signature :
 |              void* __init__(boost::python::api::object,std::string,std::string,int)
 |  
 |  __reduce__ = <unnamed Boost.Python function>(...)
 |  
 |  after_backward(...)
 |      after_backward( (Net)arg1 [, (object)arg2]) -> None :
 |      
 |          C++ signature :
 |              void after_backward(caffe:

In [9]:
print(type(net.inputs))

<type 'list'>


In [10]:
print(type(net.blobs))

<class 'collections.OrderedDict'>


In [11]:
print(dir(net.blobs['data']))

['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'channels', 'count', 'data', 'diff', 'height', 'num', 'reshape', 'shape', 'width']


In [12]:
print([(k,v) for k,v in net.blobs.items()])

[('data', <caffe._caffe.Blob object at 0x7f6d51571668>), ('conv1', <caffe._caffe.Blob object at 0x7f6d109a6ed8>)]


In [13]:
net.blobs['data']

In [22]:
net.blobs["data"].num

1

In [16]:
net.blobs["data"].channels

1

In [23]:
net.blobs["data"].height

100

In [24]:
net.blobs["data"].width

100

In [17]:
net.blobs["data"].count

10000

In [18]:
net.blobs["data"].data

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]]], dtype=float32)

In [20]:
net.blobs["data"].data.shape

(1, 1, 100, 100)

In [19]:
net.blobs["data"].diff

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]]], dtype=float32)

In [25]:
net.blobs["data"].diff.shape

(1, 1, 100, 100)

In [26]:
dir(net.blobs["conv1"])

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'channels',
 'count',
 'data',
 'diff',
 'height',
 'num',
 'reshape',
 'shape',
 'width']

In [27]:
net.blobs["conv1"].data

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]]], dtype=float32)

In [29]:
net.blobs["conv1"].data.shape

(1, 3, 96, 96)

In [28]:
net.blobs["conv1"].diff

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]]], dtype=float32)

In [30]:
[(k,v.data.shape) for k,v in net.blobs.items()]

[('data', (1, 1, 100, 100)), ('conv1', (1, 3, 96, 96))]

In [31]:
net.params

OrderedDict([('conv', <caffe._caffe.BlobVec at 0x7f6d109aab40>)])

In [32]:
type(net.params["conv"])

caffe._caffe.BlobVec

In [33]:
dir(net.params["conv"])

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__instance_size__',
 '__iter__',
 '__len__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'add_blob',
 'append',
 'extend']

In [34]:
len(net.params["conv"])

2

In [35]:
type(net.params["conv"][0])  #weight

caffe._caffe.Blob

In [36]:
net.params["conv"][0]

In [37]:
type(net.params["conv"][1])  #bias

caffe._caffe.Blob

In [38]:
net.params["conv"][1]

In [40]:
net.params["conv"][0].count

75

In [41]:
net.params["conv"][0].data

array([[[[ 0.00230441, -0.01212337,  0.00209555,  0.02048757, -0.00828044],
         [ 0.00066182,  0.00175591,  0.00517966, -0.01364826,  0.01198405],
         [ 0.01003639,  0.00858907, -0.02642966, -0.01117995,  0.00719016],
         [ 0.00505872, -0.011738  ,  0.00103667,  0.01844401, -0.0031838 ],
         [ 0.00043328, -0.01125987,  0.00052166, -0.00270148, -0.00280319]]],


       [[[-0.00563696,  0.00161255,  0.00100273, -0.00045065, -0.00399304],
         [-0.00080523,  0.00892141, -0.00234536, -0.01430306,  0.00105015],
         [ 0.01957805, -0.00369492, -0.0062302 ,  0.0043225 , -0.00117626],
         [-0.00186105, -0.00246757, -0.00218272,  0.00532596, -0.00064827],
         [ 0.0042028 ,  0.00312632,  0.00078236, -0.00362117,  0.0004766 ]]],


       [[[ 0.00967041,  0.0144755 , -0.00657883, -0.00170403, -0.03245863],
         [ 0.0031265 ,  0.00447395,  0.00946882,  0.00559208, -0.01430211],
         [ 0.00632495,  0.00459284,  0.01659666,  0.01632923,  0.00190463],
    

In [46]:
net.params["conv"][0].num

3

In [42]:
net.params["conv"][0].channels

1

In [44]:
net.params["conv"][0].height

5

In [45]:
net.params["conv"][0].width

5

In [48]:
[(k,v[0].data.shape,v[1].data.shape) for k,v in net.params.items()]

[('conv', (3, 1, 5, 5), (3,))]

In [49]:
im = np.array(Image.open('/home/lqp/caffe/examples/images/cat_gray.jpg'))  

In [50]:
im_input = im[np.newaxis, np.newaxis, :, :]  

In [62]:
net.blobs['data'].reshape(*im_input.shape)

In [63]:
net.blobs['data'].data[...] = im_input  

In [64]:
print net.blobs['data'].data.shape  

(1, 1, 360, 480)


In [65]:
net.forward()

{'conv1': array([[[[ -1.31701007e-01,  -7.79815987e-02,  -2.47457594e-01, ...,
            -6.40156209e-01,  -5.25955737e-01,  -3.90512288e-01],
          [ -2.05688074e-01,  -2.35169128e-01,  -1.85428113e-01, ...,
            -4.92316186e-01,  -4.90979195e-01,  -5.44241250e-01],
          [ -1.65241003e-01,  -3.13894451e-01,  -2.49478206e-01, ...,
            -6.15325153e-01,  -6.39151216e-01,  -4.75485295e-01],
          ..., 
          [ -2.23480046e-01,  -2.53433257e-01,  -2.47621328e-01, ...,
            -2.49264193e+00,  -9.50402319e-01,  -1.11456251e+00],
          [ -2.43851811e-01,  -4.97557223e-01,  -4.74083900e-01, ...,
            -1.64946407e-01,  -6.02019668e-01,  -1.95862758e+00],
          [ -4.75489140e-01,  -7.12440610e-01,  -5.66260397e-01, ...,
            -2.13529086e+00,  -1.80782866e+00,  -9.61293697e-01]],
 
         [[  4.06406261e-02,  -1.21277245e-03,  -4.03973274e-02, ...,
             7.94924349e-02,   1.36564359e-01,   1.32623658e-01],
          [  5.16705

In [69]:
net.blobs["conv1"].data.shape

(1, 3, 356, 476)

In [66]:
net.blobs["conv1"].data[0,:3]

array([[[ -1.31701007e-01,  -7.79815987e-02,  -2.47457594e-01, ...,
          -6.40156209e-01,  -5.25955737e-01,  -3.90512288e-01],
        [ -2.05688074e-01,  -2.35169128e-01,  -1.85428113e-01, ...,
          -4.92316186e-01,  -4.90979195e-01,  -5.44241250e-01],
        [ -1.65241003e-01,  -3.13894451e-01,  -2.49478206e-01, ...,
          -6.15325153e-01,  -6.39151216e-01,  -4.75485295e-01],
        ..., 
        [ -2.23480046e-01,  -2.53433257e-01,  -2.47621328e-01, ...,
          -2.49264193e+00,  -9.50402319e-01,  -1.11456251e+00],
        [ -2.43851811e-01,  -4.97557223e-01,  -4.74083900e-01, ...,
          -1.64946407e-01,  -6.02019668e-01,  -1.95862758e+00],
        [ -4.75489140e-01,  -7.12440610e-01,  -5.66260397e-01, ...,
          -2.13529086e+00,  -1.80782866e+00,  -9.61293697e-01]],

       [[  4.06406261e-02,  -1.21277245e-03,  -4.03973274e-02, ...,
           7.94924349e-02,   1.36564359e-01,   1.32623658e-01],
        [  5.16705811e-02,   5.66075835e-03,   1.12253297e-0

In [67]:
net.blobs["conv1"].data[0,1]

array([[ 0.04064063, -0.00121277, -0.04039733, ...,  0.07949243,
         0.13656436,  0.13262366],
       [ 0.05167058,  0.00566076,  0.01122533, ...,  0.21342002,
         0.21682514,  0.13376518],
       [ 0.06527852, -0.02949532,  0.02606035, ...,  0.30150726,
         0.19440612,  0.13229614],
       ..., 
       [ 0.04783653,  0.13881618, -0.0469519 , ...,  0.17975806,
         0.73664999,  0.89840794],
       [ 0.11497775,  0.07611807, -0.02751616, ...,  0.61717856,
         1.10158813, -0.14277995],
       [ 0.06414244, -0.12271699,  0.03615582, ...,  1.03800917,
         0.43290079,  0.13161479]], dtype=float32)

In [68]:
net.blobs["conv1"].data[0,1].shape

(356, 476)

In [70]:
net.save("/home/lqp/caffe/examples/lqp/mymodel.caffemodel")